import { Component, ElementRef, ViewChild } from '@angular/core';
import { PlantCarouselComponent } from '../plant-carousel/plant-carousel.component';

@Component({
  selector: 'app-landing',
  standalone: true,
  imports: [PlantCarouselComponent],
  templateUrl: './landing.component.html',
  styleUrl: './landing.component.scss',
})
export class LandingComponent {
  @ViewChild('aboutContent') aboutContentElement!: ElementRef;

  contentAbout: string =
    `Generally, conventional wallets that we know are made from materials such as leather, cotton textiles, or other similar materials, but in reality the use of these materials to make wallets has a significant impact in terms of greenhouse gas emissions, energy consumption, and material pollution. chemistry.

    At Green Pay, we are conscious and therefore, our main aim in creating eco-friendly wallets is to raise awareness and promote sustainable and quality alternatives.

    By using a unique and sustainable alternative like Eco-Friendly Wallet, you avoid the need to extract new natural resources, thereby reducing the energy and water demands required in conventional production. You also give a second life to a waste product with a new use that will last for a long time: our eco-friendly wallets are durable and resistant, thus guaranteeing long-term use and reducing the need for frequent replacement. This reduces overconsumption and waste generated by product obsolescence.`;

  constructor() {}

  ngAfterViewInit(): void {
    this.typeWriterEffect();
  }

  typeWriterEffect() {
    const typingText = this.aboutContentElement.nativeElement;
    const text = this.contentAbout.trim();
    let charIndex = 0;

    const type = () => {
      if (charIndex < text.length) {
        typingText.textContent += text.charAt(charIndex);
        charIndex++;
        setTimeout(type, 30);
      }
    };

    type();
  }
}
